#!/bin/bash

set -euxo pipefail

# Enable console service
mkosi-chroot systemctl unmask serial-console.service
mkosi-chroot systemctl add-wants minimal.target serial-console.service

# Deterministically set root password
PASSWORD="dqSPjo4p"
HASH=$(mkosi-chroot openssl passwd -6 -salt salt "$PASSWORD")
mkosi-chroot passwd -u root
mkosi-chroot usermod -p "$HASH" root

# Allow login by password
echo "PasswordAuthentication yes" >> "$BUILDROOT/etc/ssh/sshd_config"
