[Service]
# Clear Environment and EnvironmentFile from base service
Environment=
EnvironmentFile=

# Override environment with playground-specific values
Environment=RBUILDER_BIDDING_SHA256SUM=71954a7f0fa06a2bbd46919446816e97da8f638ee697ee32aa326ee93022e859 \
            RBUILDER_BIDDING_TAG=v1.3.6 \
            RBUILDER_BIDDING_REPO=rbuilder \
            RBUILDER_BIDDING_ARTIFACT=tbv-bidding-service
