[Build]
Environment=KERNEL_CONFIG_SNIPPETS_L2_COMMON=modules/l2/_common/kernel/config.d
WithNetwork=true

[Content]
BuildScripts=modules/l2/_common/mkosi.build
ExtraTrees=modules/l2/_common/mkosi.extra
PostInstallationScripts=modules/l2/_common/mkosi.postinst.chroot
SyncScripts=modules/l2/_common//mkosi.sync

Packages=fluent-bit
         logrotate
         prometheus-node-exporter
         prometheus-process-exporter
         rsyslog
         usrmerge
         xfsprogs

BuildPackages=golang
              libssl-dev
              unzip
              yq
