[Build]
WithNetwork=true

[Content]
BuildScripts=modules/l2/op-rbuilder/mkosi.build
ExtraTrees=modules/l2/op-rbuilder/mkosi.extra
PostInstallationScripts=modules/l2/op-rbuilder/mkosi.postinst

Packages=libtss2-dev
         sudo
         unzip

BuildPackages=golang
              libssl-dev
              rustup
              unzip
              yq
