[Include]
Include=base/base.conf
Include=bob-base/bob-base.conf
Include=bob-l2/bob-l2.conf

[Config]
Profiles=azure

[Distribution]
Mirror=https://snapshot.debian.org/archive/debian/20250526T142542Z/

[Build]
ToolsTreeMirror=https://snapshot.debian.org/archive/debian/20250526T142542Z/
