AddressFamily inet

Match User searcher
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    DisableForwarding yes

Match User sftp
    AuthorizedKeysFile none
    AuthorizedKeysCommand /usr/bin/cat /home/searcher/.ssh/authorized_keys
    AuthorizedKeysCommandUser searcher
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    DisableForwarding yes
    ChrootDirectory /persistent
    ForceCommand internal-sftp -d /searcher
