[Build]
WithNetwork=true

[Content]
BuildScripts=modules/l2/simulator/mkosi.build
ExtraTrees=modules/l2/simulator/mkosi.extra
PostInstallationScripts=modules/l2/simulator/mkosi.postinst

Packages=sudo
         unzip

BuildPackages=golang
              libssl-dev
              rustup
              unzip
              yq
