[Build]
WithNetwork=true

[Content]
BuildScripts=modules/l2/vector/mkosi.build
ExtraTrees=modules/l2/vector/mkosi.extra
PostInstallationScripts=modules/l2/vector/mkosi.postinst.chroot
BuildPackages=protobuf-compiler
              zlib1g-dev
