z /                       0755 root    root    -
d /persistent             0755 root    root    -
d /run/flashbox           0755 root    root    -
d /run/flashbox/image     0700 sandbox sandbox -
d /run/flashbox/sandbox   0700 sandbox sandbox -
d /run/flashbox/logs      0700 sandbox sandbox -
