[Build]
Environment=KERNEL_CONFIG_SNIPPETS_FLASHBOX=modules/flashbox/common/kernel/config.d
WithNetwork=true

[Content]
ExtraTrees=modules/flashbox/common/mkosi.extra/etc/containers:/etc/containers
           modules/flashbox/flashbox-stateless/mkosi.extra
BuildScripts=modules/flashbox/flashbox-stateless/mkosi.build
PostInstallationScripts=modules/flashbox/flashbox-stateless/mkosi.postinst

Packages=podman
         catatonit
         runc
         uidmap
         iptables
         openssh-server
         sudo
         libdevmapper1.02.1
         libjson-c5
         libpopt0

BuildPackages=build-essential
              git
              curl
              golang
              rustc/trixie-backports
              cargo/trixie-backports
              libcurl4t64/trixie-backports
              curl/trixie-backports
              autoconf
              automake
              libtool
              libssh-dev
              libdevmapper-dev
              libpopt-dev
              uuid-dev
              libblkid-dev
              libjson-c-dev
              gettext
              autopoint
