[Content]
ExtraTrees=modules/flashbox/observability/mkosi.extra
PostInstallationScripts=modules/flashbox/observability/mkosi.postinst

Packages=prometheus
         prometheus-node-exporter
         prometheus-process-exporter
         gettext-base
