[Build]
WithNetwork=true

[Content]
ExtraTrees=modules/flashbox/observability/mkosi.extra
PostInstallationScripts=modules/flashbox/observability/mkosi.postinst
BuildScripts=modules/flashbox/observability/mkosi.build

Packages=prometheus
         prometheus-node-exporter
         prometheus-process-exporter

BuildPackages=build-essential
              git
              golang
