[Build]
Environment=LIGHTHOUSE_BINARY
WithNetwork=true

[Content]
ExtraTrees=modules/flashbox/flashbox-l1/mkosi.extra
PostInstallationScripts=modules/flashbox/flashbox-l1/mkosi.postinst
BuildScripts=modules/flashbox/flashbox-l1/mkosi.build

BuildPackages=build-essential
              git
              gcc
              zlib1g-dev
              libzstd-dev
              libleveldb-dev
              libsnappy-dev
              libpq-dev
              libssl-dev
