[Build]
WithNetwork=true

[Content]
ExtraTrees=modules/flashbox/flashbox-l1/mkosi.extra
PostInstallationScripts=modules/flashbox/flashbox-l1/mkosi.postinst
BuildScripts=modules/flashbox/flashbox-l1/mkosi.build
