[Include]
Include=shared/mkosi.conf
Include=modules/flashbox/common/mkosi.conf
Include=modules/flashbox/flashbox-l2/mkosi.conf
Include=modules/flashbox/observability/mkosi.conf

[Config]
Profiles=gcp

[Distribution]
Snapshot=20260430T025253Z
