[Include]
Include=shared/mkosi.conf
Include=modules/flashbox/common/mkosi.conf
Include=modules/flashbox/flashbox-l1/mkosi.conf
Include=modules/flashbox/observability/mkosi.conf

[Config]
Profiles=azure,gcp

[Distribution]
Snapshot=20260301T083349Z
