[Config]
Profiles=gcp

[Distribution]
Snapshot=20260301T083349Z

[Include]
Include=shared/mkosi.conf
Include=modules/l2/_common/mkosi.conf
Include=modules/l2/_gcp/mkosi.conf
Include=modules/l2/_no_console/mkosi.conf
Include=modules/l2/_no_root_login/mkosi.conf
Include=modules/l2/op-rbuilder/mkosi.conf
