#!/bin/bash

set -euxo pipefail

# Enable systemd services

for service in \
    node-healthchecker.service \
    tdx-quote-provider.service
do
    mkosi-chroot systemctl enable "$service"
    mkosi-chroot systemctl add-wants minimal.target "$service"
done

# Create users and groups
mkosi-chroot groupadd -g 2000    optimism                             || true
mkosi-chroot useradd  -u 2002 -g optimism -m -s /bin/bash op-rbuilder || true
