[Partition]
Type=root
Format=erofs
CopyFiles=/
ExcludeFiles=/boot
ExcludeFiles=/efi
# mkosi looks for the kernel here after .finalize hooks run
ExcludeFiles=/usr/lib/modules
Label=root
Verity=data
VerityMatchKey=root
Minimize=best
