#!/bin/bash
set -euxo pipefail

# Create user and group
# NOTE: Due to a limitation in mkosi, all folders are owned by root by default
# https://github.com/systemd/mkosi/issues/3065
mkosi-chroot groupadd -r eth
mkosi-chroot useradd -r -s /bin/false -G eth op-node

# Enable op-node service
mkdir -p "$BUILDROOT/etc/systemd/system/minimal.target.wants"
mkosi-chroot systemctl enable op-node.service
ln -sf /etc/systemd/system/op-node.service "$BUILDROOT/etc/systemd/system/minimal.target.wants/"
