#!/usr/bin/env bash
# Regenerate shared/kernel/config.d/01-hardening from kernel-hardening-checker.
# Usage: make refresh-hardening
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${REPO_DIR}/shared/kernel/config.d/01-hardening"

TOOL_REPO="https://github.com/a13xp0p0v/kernel-hardening-checker"
TOOL_TAG="v0.6.17.1"
TOOL_DIR=$(mktemp -d)
trap 'rm -rf "$TOOL_DIR"' EXIT

git -c advice.detachedHead=false clone --depth 1 --branch "$TOOL_TAG" --quiet "$TOOL_REPO" "$TOOL_DIR"
TOOL_BIN="${TOOL_DIR}/bin/kernel-hardening-checker"

TOOL_VERSION=$("${TOOL_BIN}" --version 2>&1 | head -1 || echo "unknown")
GENERATED=$("${TOOL_BIN}" -g X86_64)

cat > "${OUTPUT}" <<EOF
# Generated by: ${TOOL_VERSION} -g X86_64
# ${TOOL_REPO}
# Do not edit — regenerate with: make refresh-hardening

${GENERATED}
EOF

OPTION_COUNT=$(grep -c '^CONFIG_\|^# CONFIG_' "${OUTPUT}" || true)
echo "Wrote ${OUTPUT} (${OPTION_COUNT} options, tool: ${TOOL_VERSION})"
