# Authenticated NTS sources
server time.cloudflare.com iburst nts
server nts.netnod.se iburst nts

# Refine trusted sources using cloud hypervisor when available
server 169.254.169.254 iburst minpoll 4 maxpoll 4
server 169.254.169.123 iburst minpoll 4 maxpoll 4

# Reject hypervisor clock if it is off by more than 1 second
maxdistance 1.0

# Store drift information
driftfile /var/lib/chrony/chrony.drift

# Step the system clock instead of slewing if adjustment is larger than
# one second, but only in the first three clock updates
makestep 1 3

# Enable kernel synchronization of the real-time clock
rtcsync

# Stop bad estimates upsetting machine clock
maxupdateskew 100.0
