[Build]
Environment=KERNEL_CONFIG_SNIPPETS_VERITY=modules/verity-root/kernel/config.d
            SYSTEMD_REPART_MKFS_OPTIONS_VFAT=--invariant
            # Debloated after finalize hook since mkosi looks in this directory for the kernel
            SKIP_DEBLOAT_PATHS_VERITY=/usr/lib/modules

[Output]
Format=disk
RepartDirectories=modules/verity-root/repart.d
SplitArtifacts=uki

[Content]
Bootable=yes
Bootloader=uki
KernelModulesInitrd=no
KernelCommandLine=systemd.volatile=overlay
# Init contains a hack that's only needed when initramfs is the rootfs
RemoveFiles=/init
