u bnet - - /home/bnet /bin/bash
m bnet sudo
u! lighthouse -
u! rbuilder-operator -
u! operator-api -
u! haproxy -
u! acme-le -
u! config-watchdog -
u! vector -
u! bid-scraper -
u! attested-tls-proxy-server -
g eth -
m lighthouse eth
m rbuilder-operator eth
