[Content]
ExtraTrees=modules/cvm-base/mkosi.extra
PostInstallationScripts=modules/cvm-base/unmask-systemd.sh
                        modules/cvm-base/mkosi.postinst
BuildScripts=modules/cvm-base/mkosi.build

Packages=podman
         podman-compose
         catatonit
         runc
         fuse-overlayfs
         uidmap
         passt
         cryptsetup
         iptables
         iproute2
         curl
         ca-certificates
         libdevmapper1.02.1
         libjson-c5

BuildPackages=build-essential
              git
              gcc
              golang
